<a href="https://colab.research.google.com/github/SevenPointCoffee/LiMu_DeepLearning/blob/main/%E7%BA%BF%E6%80%A7%E5%9B%9E%E5%BD%92ZERO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install -U d2l


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
%matplotlib inline
import random
import torch
from d2l import torch as d2l

In [4]:
def synthetic_data(w,b,num_examples):
  x = torch.normal(0,1,(num_examples,len(w)))
  y = torch.matmul(x,w) + b
  y += torch.normal(0,0.01,y.shape) # 增加噪音量
  return x,y.reshape((-1,1))

true_w = torch.tensor([2,-4.2])
true_b = 4.2
features,labels = synthetic_data(true_w,true_b,1000)

In [5]:
#features.shape
features[0]

tensor([ 2.4974, -2.4777])

In [6]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # 这些样本是随机读取的，没有特定的顺序
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        print(batch_indices.shape)
        yield features[batch_indices], labels[batch_indices]

In [7]:
batch_size = 10
for x,y in data_iter(batch_size,features,labels):
  print(x,"\n",y)
  break

torch.Size([10])
tensor([[ 0.3094, -1.6330],
        [-0.1706,  1.3460],
        [-0.6643,  0.3919],
        [ 0.2529, -0.7918],
        [-0.6026,  0.1183],
        [-0.7561,  0.2217],
        [-1.5687,  0.3132],
        [ 1.1147, -0.9098],
        [-0.6707, -0.2017],
        [-1.9560, -1.3737]]) 
 tensor([[11.6755],
        [-1.7820],
        [ 1.2278],
        [ 8.0337],
        [ 2.5107],
        [ 1.7480],
        [-0.2452],
        [10.2483],
        [ 3.6955],
        [ 6.0430]])


In [8]:
w = torch.normal(0,0.01,size =(2,1),requires_grad = True) #随机一个数
b = torch.zeros(1,requires_grad = True)

In [9]:
def linreg(x,w,b):
  return torch.matmul(x,w)+b # 线性回归模型

In [10]:
def squared_loss(y_hat,y):
  return (y_hat-y.reshape(y_hat.shape))**2/2

In [11]:
def sgd(params,lr,batch_size):
  with torch.no_grad():
    for param in params:
      param -= lr*param.grad/batch_size
      param.grad.zero_()